import test from "node:test";
import assert from "node:assert/strict";
import { inspectImport, importConfig, importSource } from "../src/core/import-pipeline.js";
import { getRuntimeSource } from "../src/core/sensitive-source.js";
import { classifyImportSource, validateSubscriptionUrl } from "../src/core/subscription.js";

const CLASH = ["proxies:", "  - name: US-1", "    type: socks5", "    server: us.example", "    port: 1080", "  - name: JP-1", "    type: socks5", "    server: jp.example", "    port: 1080"].join("\n");

test("import inspection automatically binds Clash YAML to Mihomo", () => { const result = inspectImport(CLASH); assert.equal(result.binding.kernel, "mihomo"); assert.equal(result.binding.mode, "automatic"); assert.equal(result.binding.requiresConfirmation, false); assert.equal(result.detection.kind, "clash-yaml"); });
test("import inspection resolves VLESS share links without kernel selection", () => { const result = inspectImport("vless://user@example.com:443?security=tls#US"); assert.equal(result.binding.mode, "automatic"); assert.equal(result.binding.requiresConfirmation, false); assert.equal(result.detection.protocol, "vless"); assert.deepEqual(result.binding.candidates, ["mihomo", "sing-box", "xray"]); });
test("automatic detection is exposed as an observable decision", () => { const result = inspectImport(CLASH); assert.equal(result.binding.decision.action, "detectKernelCompatibility"); assert.equal(result.binding.decision.requiresUserChoice, false); assert.deepEqual(result.binding.decision.options, ["mihomo"]); });
test("multi-runtime detection remains automatic", () => { const result = inspectImport("vless://user@example.com:443?security=tls#US"); assert.equal(result.binding.decision.action, "detectKernelCompatibility"); assert.equal(result.binding.decision.requiresUserChoice, false); assert.deepEqual(result.binding.decision.options, ["mihomo", "sing-box", "xray"]); });
test("explicit kernel binding is preserved and incompatible binding is rejected", () => { const explicit = inspectImport(CLASH, { kernel: "mihomo" }); assert.equal(explicit.binding.kernel, "mihomo"); assert.equal(explicit.binding.mode, "explicit"); assert.throws(() => inspectImport(CLASH, { kernel: "xray" }), /selected kernel is incompatible with detected format/); });
test("import produces a unified model without silently limiting nodes", () => { const result = importConfig(CLASH); assert.equal(result.model.nodeCount, 2); assert.equal(result.model.nodeLimit, null); assert.equal(result.model.unifiedConfig.kernel, "mihomo"); assert.equal(result.model.unifiedConfig.nodes.length, 2); });
test("import produces a verified native runtime handoff for cold start", () => { const result = importConfig(CLASH); assert.equal(result.runtimeHandoff.kernel, "mihomo"); assert.match(result.runtimeHandoff.configuration, /US-1/); assert.equal(result.runtimeHandoff.executionIntent.mode, "proxy"); assert.equal(result.runtimeHandoff.executionIntent.target, "US-1"); assert.equal(result.runtimeHandoff.compilerValidation.ok, true); });
test("import applies node limit only when explicitly supplied", () => { const result = importConfig(CLASH, { maxNodes: 1 }); assert.equal(result.model.nodeCount, 1); assert.equal(result.model.nodeLimit, 1); });
test("structured sing-box import excludes non-proxy outbounds while preserving safe native groups", () => { const result = importConfig({ inbounds: [], outbounds: [{ type: "vless", tag: "us", server: "us.example", server_port: 443, uuid: "u1" }, { type: "selector", tag: "auto", outbounds: ["us"] }, { type: "direct", tag: "direct" }], route: { rules: [] } }, { kernel: "sing-box" }); assert.equal(result.model.nodeCount, 1); assert.equal(result.model.nodes[0].id, "us"); assert.equal(result.model.unifiedConfig.kernel, "sing-box"); assert.equal(result.model.unifiedConfig.groups.length, 1); assert.equal(result.model.unifiedConfig.groups[0].type, "selector"); assert.equal(result.model.unifiedConfig.groups[0].name, "auto"); });
test("native source is preserved outside the enumerable unified model for lossless runtime handoff", () => { const input = { inbounds: [], outbounds: [{ type: "vless", tag: "us", server: "us.example", server_port: 443, uuid: "u1", custom_native_field: { enabled: true } }], route: { rules: [] } }; const result = importConfig(input); assert.equal(result.binding.kernel, "sing-box"); assert.equal(result.model.unifiedConfig.native.format, "structured"); assert.equal(result.model.unifiedConfig.native.runtimeCandidates[0], "sing-box"); assert.equal(result.model.unifiedConfig.native.source.outbounds, undefined); assert.equal(getRuntimeSource(result.sourceVault).outbounds[0].custom_native_field.enabled, true); });
test("classifies subscription URLs, local files, and text independently", () => { assert.deepEqual(classifyImportSource("https://example.com/sub"), { type: "url", url: "https://example.com/sub" }); assert.deepEqual(classifyImportSource({ type: "file", name: "nodes.yaml", content: CLASH }), { type: "file", name: "nodes.yaml", content: CLASH }); assert.deepEqual(classifyImportSource("vless://a@example.com:443"), { type: "text", content: "vless://a@example.com:443" }); });
test("imports multiple mixed-protocol single nodes line-by-line without kernel selection", () => { const input = ["vless://u@example.com:443#VLESS", "trojan://p@example.com:443#Trojan", "ss://YWVzLTEyOC1nY206cGFzcw==@example.com:443#SS", "hysteria2://password@example.com:443#HY2"].join("\\n"); const result = importConfig(input); assert.equal(result.model.nodeCount, 4); assert.deepEqual(result.model.nodes.map((node) => node.protocol), ["vless", "trojan", "ss", "hysteria2"]); assert.equal(result.binding.mode, "automatic"); });
test("imports local configuration file content without requiring kernel selection", () => { const result = importSource({ type: "file", name: "config.yaml", content: CLASH }); return result.then((value) => { assert.equal(value.model.nodeCount, 2); assert.equal(value.detection.kind, "clash-yaml"); }); });
test("imports a subscription URL through an injected fetcher", async () => { const result = await importSource("https://example.com/sub", { fetcher: async () => ({ ok: true, text: async () => "vless://u@example.com:443#US" }) }); assert.equal(result.model.nodeCount, 1); assert.equal(result.model.nodes[0].protocol, "vless"); });
test("rejects subscription URLs with embedded credentials or unsupported schemes", () => { assert.throws(() => validateSubscriptionUrl("ftp://example.com/sub"), /http or https/); assert.throws(() => validateSubscriptionUrl("https://user:pass@example.com/sub"), /embedded credentials/); });
