package app.angelanexus

enum class AndroidUiStatus {
    READY,
    SELECTING_CONFIG,
    IMPORTING_CONFIG,
    CONFIG_DELIVERED_TO_CORE,
    CONFIG_NOT_STARTABLE,
    CORE_RUNTIME_UNAVAILABLE,
    VPN_RUNTIME_NOT_READY,
    TRANSPARENT_MODE_UNAVAILABLE,
    ROOT_MODE_BACKEND_PENDING
}
